<a href="https://colab.research.google.com/github/afnanhabib787/Artificial-Intelligence/blob/main/Manual_feature_extraction_Assignment_Afnan_Habib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Function to perform convolution operation

In [ ]:
def convolution2d(image, kernel, stride):
    
    kernel_rows, kernel_columns = kernel.shape
    image_rows, image_columns = image.shape

    output_rows = (image_rows - kernel_rows) // stride + 1
    
    output_columns = (image_rows - kernel_columns) // stride + 1
    
    new_image = np.zeros((output_rows, output_columns)).astype(np.float32)

    for y in range(0, output_rows):
        for x in range(0, output_columns):
            new_image[y][x] = np.sum(image[y * stride:y * stride + kernel_rows, x * stride:x * stride + kernel_columns] * kernel).astype(np.float32)
    return new_image

## Random 2d array generation with size of (32,32)
## Random kernel (filter) with size of (5,5)

In [ ]:
import numpy as np
image = np.random.randint(0,255, size=(32,32))

kernel = np.random.randint(-1,2, size=(5,5))
print("Image shape: {} \n {} \n\n Kernel shape: {} \n {}".format(image.shape, image, kernel.shape, kernel))

Image shape: (32, 32) 
 [[127 101 146 ... 106  14 100]
 [241 210 178 ...  81 195 135]
 [ 84 140  68 ... 228  58 104]
 ...
 [180  60  42 ... 113 246 249]
 [142 207 232 ... 125 122  76]
 [232  43 176 ... 122 171 199]] 

 Kernel shape: (5, 5) 
 [[ 0 -1  0  1 -1]
 [ 0 -1  1  1  0]
 [ 1  0  0  1  1]
 [ 1  0  1  0  0]
 [ 1 -1  1  0 -1]]


## Convolving Image with kernel, before convolution the size of image was (32,32), and after convoltion the size of image is (28,28)

In [ ]:
convolved = convolution2d(image,kernel,1)
print('Size of image after first convolution: ', convolved.shape)

Size of image after first convolution:  (28, 28)


## Applying ReLu function, the negative values are 0

In [ ]:
convolved_relu = np.maximum(convolved, 0)
print(convolved_relu)

[[ 721.  819.   31.  911.  495.  642.  398.  654.   66.  717.  588.  504.
  1017.  612.  632.  616.  339.  465.  427.  829.  757.  175.  700.  683.
   140.  944.  715.  153.]
 [ 183.  608.  640.  832.  474.  321.  703.  667.  712.  939.  961.  843.
   415. 1071.  389.  618. 1042.  687.  717. 1099.  658.  695.  575.  732.
   419.  504.  952.  810.]
 [ 463.  449.  229. 1064.  795.  586.  690.  934.  732.  564. 1431.  628.
     0.  923. 1028.  360.  473. 1320.  655.  504.  609. 1328.  124.  776.
   831.  564.  649.  732.]
 [ 589.  597.  509.  377. 1049.  822.  472.  736.  536.  538.  998.  282.
   530. 1019.  161. 1203.  399.  795.  839.  762.  674.  833.  736.  720.
   359.  780.  788.  596.]
 [ 586.  899.  477.  566.  812.  475.  412.  820.   43.  789.  453.  695.
   879.  908.    0. 1413.  738.  814.  988. 1010.  227.  375.  734.  455.
   249.  730.  938.  625.]
 [ 569. 1165.  397.  785.  546.  518.  574.  457.  645.  395.  919.  367.
   646. 1130.  367.  940.  455.  986. 1083.  528.  

## Applying MaxPooling with window size of (2,2), After applying MaxPooling the image size is (14, 14)

In [ ]:
import numpy as np
import skimage.measure


convolved_relu_max_pooling = skimage.measure.block_reduce(convolved_relu, (2,2), np.max)
print("Image size: ", convolved_relu_max_pooling.shape)

Image size:  (14, 14)


## Applying convolution second time 

In [ ]:
convolved2 = convolution2d(convolved_relu_max_pooling,kernel,1)
print("Image size: ", convolved2.shape)

Image size:  (10, 10)


## Applying ReLu function second time

In [ ]:
convolved2_relu = np.maximum(convolved2, 0)
print(convolved2_relu)

[[4114. 4767. 4463. 6181. 5421. 5069. 5610. 3994. 3823. 4268.]
 [4854. 3791. 5384. 5473. 5426. 4797. 4838. 4210. 3299. 5395.]
 [5325. 4907. 5175. 5047. 6709. 2898. 4979. 4178. 5045. 4977.]
 [4293. 5170. 4704. 4618. 6760. 3186. 4280. 3113. 5784. 4778.]
 [4300. 5159. 3784. 4554. 5552. 2713. 4480. 2619. 4423. 5070.]
 [3139. 4769. 4410. 3705. 4881. 1985. 5957. 3013. 4372. 4964.]
 [3092. 5679. 4895. 3380. 5056. 3247. 4675. 3911. 5566. 4181.]
 [3719. 4701. 5185. 4698. 4806. 3740. 4546. 4964. 5018. 5418.]
 [4171. 4466. 5534. 4968. 3679. 4735. 5171. 4306. 4952. 4995.]
 [3118. 4608. 4611. 4621. 3138. 5155. 5022. 4956. 5291. 5426.]]


## Applying MaxPooling, image size is (5, 5) now

In [ ]:
convolved2_relu_max_pooling = skimage.measure.block_reduce(convolved2_relu, (2,2), np.max)
print("Image size: ", convolved2_relu_max_pooling.shape)

Image size:  (5, 5)


## -------------------------- END --------------------------